version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    entrypoint:
      - yarn
      - run
      - start
      
volumes:
  reserved: