name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag maulanadsgn/pingpongnode:latest
    - name: Push the latest Docker image
      run: docker push maulanadsgn/pingpongnode:latest
